`ifndef CACHE_CACOP_DEFS_VH
`define CACHE_CACOP_DEFS_VH

// code[4:3] 
`define CACHE_CACOP_CODE_STORE_TAG 2'b00
`define CACHE_CACOP_CODE_INDEX_INV 2'b01
`define CACHE_CACOP_CODE_HIT_INV 2'b10

// code[2:0] 
`define CACHE_CACOP_TARGET_ICACHE 3'b000
`define CACHE_CACOP_TARGET_DCACHE 3'b001
`define CACHE_CACOP_TARGET_L2     3'b010

`define CACHE_CACOP_MAINT_STORE_TAG 2'd0
`define CACHE_CACOP_MAINT_INDEX_INV 2'd1
`define CACHE_CACOP_MAINT_HIT_INV 2'd2

`endif
